version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "zod"
        versions:
          - "<3.25.76"
          - ">3.25.76"
    groups:
      eslint:
        patterns:
          - '*eslint*'
      prettier:
        patterns:
          - '*prettier*'
      security-all:
        applies-to: 'security-updates'
        patterns:
          - '*'
      version-all:
        applies-to: 'version-updates'
        patterns:
          - '*'

