name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Set environment variables for production
        run: |
          # Create a copy of the production env file
          cp client/.env.production client/.env.production.bak
          
          # Replace placeholder values with GitHub secrets
          sed -i 's|your-supabase-url-here|${{ secrets.VITE_SUPABASE_URL }}|g' client/.env.production
          sed -i 's|your-supabase-anon-key-here|${{ secrets.VITE_SUPABASE_ANON_KEY }}|g' client/.env.production
          sed -i 's|your-sentry-dsn-here|${{ secrets.VITE_SENTRY_DSN }}|g' client/.env.production
          
          # Update API URL if it's using the Railway placeholder or needs to be overridden
          if [ -n "${{ secrets.VITE_API_URL }}" ]; then
            sed -i 's|VITE_API_URL=.*|VITE_API_URL=${{ secrets.VITE_API_URL }}|g' client/.env.production
          fi
          
          # Show the final result for debugging (without sensitive values)
          echo "Production environment file created:"
          grep -E '^[^#]' client/.env.production | sed 's/=.*/=***/' || true

      - name: Build project
        run: npm run --workspace=client build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: client/dist
